import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: {
    default: "Dream Vacations by Richard Johnson & Travel Advisors Group - Travel Agent in Winter Garden FL",
    template: "%s | Dream Vacations by Richard Johnson & Travel Advisors Group",
  },
  description:
    "Your trusted travel agent in Winter Garden, FL. Richard Johnson & Travel Advisors Group specializes in crafting personalized dream vacations, European cruises, destination wedding packages, and all-inclusive getaways.",
  keywords: [
    "Travel Agent Winter Garden FL",
    "Richard Johnson Travel",
    "Dream Vacations",
    "Winter Garden Travel Agent",
    "Cruises Winter Garden",
    "European Cruises",
    "Destination Wedding Packages",
    "All-inclusive vacations Florida",
    "Honeymoons Winter Garden",
    "Travel Advisors Group",
    "Richard Johnson & Travel Advisors Group",
  ],
  openGraph: {
    title: "Dream Vacations by Richard Johnson & Travel Advisors Group - Travel Agent in Winter Garden FL",
    description:
      "Your trusted travel agent in Winter Garden, FL. Richard Johnson & Travel Advisors Group specializes in crafting personalized dream vacations, European cruises, destination wedding packages, and all-inclusive getaways.",
    url: "https://your-domain.com", // Replace with actual domain
    siteName: "Dream Vacations by Richard Johnson & Travel Advisors Group",
    images: [
      {
        url: "/opengraph-image.png", // This will be generated by opengraph-image.tsx
        width: 1200,
        height: 630,
        alt: "Dream Vacations by Richard Johnson & Travel Advisors Group",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Dream Vacations by Richard Johnson & Travel Advisors Group - Travel Agent in Winter Garden FL",
    description:
      "Your trusted travel agent in Winter Garden, FL. Richard Johnson & Travel Advisors Group specializes in crafting personalized dream vacations, European cruises, destination wedding packages, and all-inclusive getaways.",
    images: ["/opengraph-image.png"], // This will be generated by opengraph-image.tsx
  },
    generator: 'v0.dev'
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
